spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/db_event_catalog}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${RESERVAE_KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/reservae}

resilience4j:
  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 10s
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 10
      foo-bar:
        max-concurrent-calls: 20
  retry:
    instances:
      foo-bar:
        max-attempts: 7
        wait-duration: 1s
        enable-exponential-backoff: true