server:
  port: 8000

spring:
  application:
    name: user-profile-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev

reservae:
  security:
    required-audience: reservae-api

springdoc:
  api-docs:
    path: /${spring.application.name}/v3/api-docs