server:
  port: 8300

spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev
  kafka:
    bootstrap-servers: ${reservae.config.kafka.server-url}
    admin:
      fail-fast: false

springdoc:
  api-docs:
    path: /${spring.application.name}/v3/api-docs

reservae:
  config:
    kafka:
      server-url: localhost:29092
      consumer-groups:
        resultado-reserva: order-service-reservation-result
        sessao-pagamento-criada: order-service-payment-session-created
        pagamento-aprovado: order-service-payment-approved
        pagamento-falhou: order-service-payment-failed
      topics:
        reserva-solicitada: reservae.order.reservation-requested.v1
        resultado-reserva: reservae.inventory.reservation-result.v1
        sessao-pagamento-criada: reservae.payment.session-created.v1
        pagamento-solicitado: reservae.payment.requested.v1
        pagamento-aprovado: reservae.payment.approved.v1
        pagamento-falhou: reservae.payment.failed.v1
        notificacao-pagamento-pendente: reservae.notification.payment-pending-requested.v1
        notificacao-pagamento-confirmado: reservae.notification.payment-confirmed-requested.v1
        notificacao-pagamento-falhou: reservae.notification.payment-failed-requested.v1
        pedido-confirmado: reservae.order.confirmed.v1
  security:
    required-audience: reservae-api