server:
  port: 8200

spring:
  application:
    name: inventory-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev
  kafka:
    bootstrap-servers: ${reservae.config.kafka.server-url}
    admin:
      fail-fast: false

springdoc:
  api-docs:
    path: /${spring.application.name}/v3/api-docs

reservae:
  config:
    reservation:
      ttl-minutes: 30
    kafka:
      server-url: localhost:29092
      consumer-groups:
        reserva-solicitada: inventory-service-reservation-requested
        pagamento-aprovado: inventory-service-payment-approved
        pagamento-falhou: inventory-service-payment-failed
      topics:
        reserva-solicitada: reservae.order.reservation-requested.v1
        resultado-reserva: reservae.inventory.reservation-result.v1
        pagamento-aprovado: reservae.payment.approved.v1
        pagamento-falhou: reservae.payment.failed.v1
  security:
    required-audience: reservae-api