spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/db_ticket}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${RESERVAE_KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/reservae}