server:
  port: 8100

spring:
  application:
    name: event-catalog-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev

springdoc:
  api-docs:
    path: /${spring.application.name}/v3/api-docs

reservae:
  security:
    required-audience: reservae-api