server:
  port: 8400

spring:
  application:
    name: payment-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev
  kafka:
    bootstrap-servers: ${reservae.config.kafka.server-url}
    admin:
      fail-fast: false

reservae:
  config:
    kafka:
      server-url: localhost:29092
      consumer-groups:
        pagamento-solicitado: payment-service-payment-requested
      topics:
        pagamento-solicitado: reservae.payment.requested.v1
        sessao-pagamento-criada: reservae.payment.session-created.v1
        pagamento-aprovado: reservae.payment.approved.v1
        pagamento-falhou: reservae.payment.failed.v1
  security:
    required-audience: reservae-api

springdoc:
  api-docs:
    path: /${spring.application.name}/v3/api-docs