name: docker-reservae

services:
  user-profile-service-postgres-db:
    image: postgres:18.4
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_user_profile
    ports:
      - '5432:5432'
    volumes:
      - postgres_user_profile_service_data:/var/lib/postgresql

  event-catalog-service-postgres-db:
    image: postgres:18.4
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_event_catalog
    ports:
      - '5433:5432'
    volumes:
      - postgres_event_catalog_service_data:/var/lib/postgresql

  inventory-service-redis-db:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_inventory_service_data:/data

  order-service-postgres-db:
    image: postgres:18.4
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_order
    ports:
      - '5434:5432'
    volumes:
      - postgres_order_service_data:/var/lib/postgresql

  payment-service-postgres-db:
    image: postgres:18.4
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_payment
    ports:
      - '5436:5432'
    volumes:
      - postgres_payment_service_data:/var/lib/postgresql
  
  ticket-service-postgres-db:
    image: postgres:18.4
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_ticket
    ports:
      - '5435:5432'
    volumes:
      - postgres_ticket_service_data:/var/lib/postgresql

  notification-service-mongodb-db:
    image: mongo:7.0
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongodb_notification_service_data:/data/db

  keycloak:
    image: quay.io/keycloak/keycloak:26.6.3
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command:
      - start-dev
      - --spi-theme--static-max-age=-1
      - --spi-theme--cache-themes=false
      - --spi-theme--cache-templates=false
    volumes:
      - ./infrastructure/keycloak/themes:/opt/keycloak/themes
      - ./infrastructure/keycloak/backups:/opt/keycloak/backups
      - keycloak_data:/opt/keycloak/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.12
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.12
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092, PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "29092:29092"

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    ports:
      - "8090:8080"

  stripe-cli:
    image: stripe/stripe-cli:latest
    restart: unless-stopped
    command: listen --api-key ${STRIPE_SECRET_KEY} --forward-to http://host.docker.internal:8400/payment-service/api/payments/webhooks/v1/stripe

volumes:
  postgres_user_profile_service_data:
  postgres_event_catalog_service_data:
  redis_inventory_service_data:
  postgres_order_service_data:
  postgres_payment_service_data:
  postgres_ticket_service_data:
  mongodb_notification_service_data:
  keycloak_data: